[project]
name = "pds-yahtzee"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]
